#!/bin/bash

set -e

echo "pre-flight checks:"

echo "Check postgresfriends.json syntax ..."
jq -e "." < postgresfriends.json > /dev/null

echo "Verifying postgresfriends.json data ..."
./bin/verify-data.py < postgresfriends.json

echo "Check for 'Mastadon' instead of 'Mastodon' ..."
if grep -q 'Mastadon' postgresfriends.json;
then
    echo "String 'Mastadon' found in postgresfriends.json"
    exit 1
fi
