#!/bin/bash

set -e

echo "pre-flight checks:"

echo "Check postgresfriends.json syntax ..."
jq -e "." < postgresfriends.json > /dev/null

echo "Verifying postgresfriends.json data ..."
./bin/verify-data.py < postgresfriends.json

echo "Check for 'Mastadon' instead of 'Mastodon' ..."
if grep -q 'Mastadon' postgresfriends.json;
then
    echo "String 'Mastadon' found in postgresfriends.json"
    exit 1
fi

echo "Check for 'Linkedin' instead of 'LinkedIn' ..."
if grep -q 'Linkedin' postgresfriends.json;
then
    echo "String 'Linkedin' found in postgresfriends.json"
    exit 1
fi

echo "Check for 'BlueSky' instead of 'Bluesky' ..."
if grep -q 'BlueSky' postgresfriends.json;
then
    echo "String 'BlueSky' found in postgresfriends.json"
    exit 1
fi

echo "Check for 'Youtube' instead of 'YouTube' ..."
if grep -q 'Youtube' postgresfriends.json;
then
    echo "String 'Youtube' found in postgresfriends.json"
    exit 1
fi

echo "Check postgresprojects.json syntax ..."
jq -e "." < postgresprojects.json > /dev/null

echo "Verifying postgresprojects.json data ..."
./bin/verify-data.py < postgresprojects.json

echo "Check for 'Mastadon' instead of 'Mastodon' ..."
if grep -q 'Mastadon' postgresprojects.json;
then
    echo "String 'Mastadon' found in postgresprojects.json"
    exit 1
fi

echo "Check for 'Linkedin' instead of 'LinkedIn' ..."
if grep -q 'Linkedin' postgresprojects.json;
then
    echo "String 'Linkedin' found in postgresprojects.json"
    exit 1
fi

echo "Check for 'BlueSky' instead of 'Bluesky' ..."
if grep -q 'BlueSky' postgresprojects.json;
then
    echo "String 'BlueSky' found in postgresprojects.json"
    exit 1
fi

echo "Check for 'Youtube' instead of 'YouTube' ..."
if grep -q 'Youtube' postgresprojects.json;
then
    echo "String 'Youtube' found in postgresprojects.json"
    exit 1
fi
